### ISSUE TITLE
docker部署报错

### ISSUE THREAD

**Issue by zsbai** [scavin/docker-EFBv2#7]
```
Traceback (most recent call last):
  File "/usr/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 268, in main
    conf = config.load_config()
  File "/usr/lib/python3.8/site-packages/ehforwarderbot/config.py", line 75, in load_config
    raise ValueError(_("\"{}\" is not found.").format(i))
ValueError: "catbaron.sticker2img" is not found.
Traceback (most recent call last):
  File "/usr/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 268, in main
    conf = config.load_config()
  File "/usr/lib/python3.8/site-packages/ehforwarderbot/config.py", line 75, in load_config
    raise ValueError(_("\"{}\" is not found.").format(i))
ValueError: "catbaron.sticker2img" is not found.
```
顺带提一下，我用readme中实例的dockercompose文件会出现(root) Additional property efbv2 is not allowed

**Comment by zsbai** [comment]
配置文件中删除catbaron.sticker2img后解决
